### PR TITLE
Disallow users from importing packages

### PR DESCRIPTION
**Pull request by ghost**
Users are able to gain shell access to the server by importing scala.sys.process._ 

This is a hotfix that disables scripts from running if it contains the string "import". A later patch should be made that handles this more elegantly since it can't distinguish an actual import from a string containing the word.

### CODE REVIEW

**Comment by ghost** [comment]
Next step is defining an import whitelist. java.util.Date is fine - java.io.File isn't.

**Comment by yankay** [comment]
The code has been merged to a new branch 'security'.
For some example can not run correctly without 'import' keyword, it cannot merged to the 'master' right now.
I've send you a email to explain this.
It's a good idea to block 'import'.
If I'm an attacker, 
- I can write Concurrent 'while true' to consume CPU resource.
- I would write 'new Int[MAX]' to consume the Memory Resource
- I also can open a lot of file to consume the File Handle Resource.
- I also can download/upload to consume Network Resource.

The worst of all, the site may be suffered a lot form DDOS for it can only run <100 request of running code at the same time. 
Network and Concurrent is an important example in the tour.
There lot of way to destroy without import package.
I think there a long way to let it safer.

There are some existing opensource interactive Language Tour, such as GoLang Tour. I would read their code, and share their way with you. 

Thank you very much for the suggestion and code.

**Comment by yankay** [comment]
Would you mind to added your name in the author column at foot of page?
Weclome

**Comment by ghost** [comment]
I don't mind.

I'm working on a patch to correct the regression you pointed out.

Thank you,
--Chris

**Comment by jimschubert** [comment]
I've issued a pull request for a policy-oriented security change which should be a better option than whitelisting imports. The policy file will allow for whitelisting URLs, preventing file execution/directory listing, and reading system properties or settings.  I just couldn't figure out how to get the Remote Actor example to work properly so I didn't request a merge into `master` but into the `security` branch.

**Pull request merged**
